import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/(styles)/globals.css";
import NextAuthSessionProvider from "@/providers/sessionProvider";
import MenuComponent from "@/components/MenuComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: {
        default: `Adriano Cobuccio: Home`,
        template: `Adriano Cobuccio: %s`,
    },
    description: "Generated by create next app",
};

export default function RootLayout(
    {children}: Readonly<{ children: React.ReactNode; }>
) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MenuComponent></MenuComponent>
                <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
            </body>
        </html>
    );
}
